baseurl = "https://alanliddell.com/"
languageCode = "en-us"
title = "Alan Liddell"
author = "Alan Liddell"
theme = "hugo-clarity"

DefaultContentLanguage = "en"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
author = "Alan Liddell"
enableMathNotation = true
introDescription = "I do math."
codeLineNumbers = true
since = 2020
