[[main]]
  name = "About"
  url = "about/"
  weight = -110

[[main]]
  name = "Posts"
  url = "posts/"
  weight = -109

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -109
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"

[[main]]
  name = "Projects"
  url = "projects/"
  weight = -108

[[main]]
  name = "Running"
  url = "running/"
  weight = -107
